files:
  - source: /com_sermonspeaker/admin/language/en-GB/*.ini
    translation: /com_sermonspeaker/admin/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /com_sermonspeaker/site/language/en-GB/*.ini
    translation: /com_sermonspeaker/site/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_latestsermons/language/en-GB/*.ini
    translation: /mod_latestsermons/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_related_sermons/language/en-GB/*.ini
    translation: /mod_related_sermons/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_sermonarchive/language/en-GB/*.ini
    translation: /mod_sermonarchive/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_sermoncast/language/en-GB/*.ini
    translation: /mod_sermoncast/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_sermonspeaker/language/en-GB/*.ini
    translation: /mod_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_sermonspeaker_admin/language/en-GB/*.ini
    translation: /mod_sermonspeaker_admin/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /mod_sermonupload/language/en-GB/*.ini
    translation: /mod_sermonupload/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_content_autotweetsermonspeaker/language/en-GB/*.ini
    translation: /plg_content_autotweetsermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_content_sermonspeaker/language/en-GB/*.ini
    translation: /plg_content_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_editors_xtd_sermonspeaker/language/en-GB/*.ini
    translation: /plg_editors_xtd_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
   - source: /plg_finder_sermonspeaker/language/en-GB/*.ini
    translation: /plg_finder_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
    type: ini
  - source: /plg_quickicon_sermonspeaker/language/en-GB/*.ini
    translation: /plg_quickicon_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_search_sermonspeaker/language/en-GB/*.ini
    translation: /plg_search_sermonspeaker/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_sermonspeaker_generic/language/en-GB/*.ini
    translation: /plg_sermonspeaker_generic/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_sermonspeaker_jwplayer7/language/en-GB/*.ini
    translation: /plg_sermonspeaker_jwplayer7/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_sermonspeaker_mediaelement/language/en-GB/*.ini
    translation: /plg_sermonspeaker_mediaelement/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_sermonspeaker_pixelout/language/en-GB/*.ini
    translation: /plg_sermonspeaker_pixelout/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /plg_sermonspeaker_vimeo/language/en-GB/*.ini
    translation: /plg_sermonspeaker_vimeo/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
